# Generated by Django 5.2.14 on 2026-05-26 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('player', 'Player'), ('scorekeeper', 'Scorekeeper'), ('manager', 'Manager')], default='player', max_length=30)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('can_manage_team', models.BooleanField(default=False)),
                ('can_start_games', models.BooleanField(default=False)),
                ('can_score_games', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_player_profiles', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'ordering': ['-is_active', 'display_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['owner', 'archived_at', 'name'], name='teams_team_owner_i_a838b9_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['archived_at', 'name'], name='teams_team_archive_2d42ea_idx'),
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['team', 'is_active', 'display_name'], name='teams_teamp_team_id_ab330a_idx'),
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['linked_user', 'is_active'], name='teams_teamp_linked__4dc426_idx'),
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['team', 'can_manage_team', 'is_active'], name='teams_teamp_team_id_bbfe08_idx'),
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['team', 'can_start_games', 'is_active'], name='teams_teamp_team_id_df2228_idx'),
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['team', 'can_score_games', 'is_active'], name='teams_teamp_team_id_63028f_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('linked_user__isnull', False)), fields=('team', 'linked_user'), name='unique_active_team_linked_user'),
        ),
    ]
