# Generated by Django 5.2.14 on 2026-05-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='role',
        ),
    ]
