# Generated by Django 5.2.14 on 2026-05-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_teamplayer_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teamplayer',
            name='teams_teamp_team_id_bbfe08_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamplayer',
            name='teams_teamp_team_id_df2228_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamplayer',
            name='teams_teamp_team_id_63028f_idx',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='can_manage_team',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='can_score_games',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='can_start_games',
        ),
    ]
