# Generated by Codex on 2026-05-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_remove_teamplayer_teams_teamp_team_id_bbfe08_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="city",
        ),
    ]
