# Generated by Django 5.2.14 on 2026-05-13 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('batting_category', models.CharField(choices=[('unspecified', 'Unspecified'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='unspecified', max_length=20)),
                ('lineup_position', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['lineup_position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('live', 'Live'), ('final', 'Final')], default='setup', max_length=20)),
                ('scheduled_innings', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('inning', models.PositiveSmallIntegerField(default=1)),
                ('half_inning', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=10)),
                ('outs', models.PositiveSmallIntegerField(default=0)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('current_home_batter_index', models.PositiveIntegerField(default=0)),
                ('current_away_batter_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('runner_on_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_runner_on_first', to='games.gameplayer')),
                ('runner_on_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_runner_on_second', to='games.gameplayer')),
                ('runner_on_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_runner_on_third', to='games.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('batting_order_mode', models.CharField(choices=[('manual', 'Manual'), ('random', 'Random'), ('rule_based', 'Rule Based')], default='manual', max_length=20)),
                ('lineup_rule_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gameteam'),
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('game_started', 'Game Started'), ('plate_appearance', 'Plate Appearance'), ('score_revision', 'Score Revision'), ('inning_limit_revision', 'Inning Limit Revision'), ('runner_revision', 'Runner Revision'), ('game_finalized', 'Game Finalized')], max_length=40)),
                ('plate_appearance_result', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('home_run', 'Home Run'), ('walk', 'Walk'), ('strikeout', 'Strikeout'), ('ground_out', 'Ground Out'), ('fly_out', 'Fly Out'), ('error', 'Error'), ('fielders_choice', "Fielder's Choice")], max_length=40, null=True)),
                ('inning', models.PositiveSmallIntegerField()),
                ('half_inning', models.CharField(max_length=10)),
                ('outs_before', models.PositiveSmallIntegerField()),
                ('outs_after', models.PositiveSmallIntegerField()),
                ('runs_scored', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state_before', models.JSONField(default=dict)),
                ('state_after', models.JSONField(default=dict)),
                ('is_undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.game')),
                ('batter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_batter', to='games.gameplayer')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='games.gameteam')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameteam',
            constraint=models.UniqueConstraint(fields=('game', 'side'), name='unique_team_side_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game_team', 'lineup_position'), name='unique_lineup_position_per_team'),
        ),
        migrations.AddConstraint(
            model_name='gameevent',
            constraint=models.UniqueConstraint(fields=('game', 'sequence_number'), name='unique_game_event_sequence_per_game'),
        ),
    ]
