# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_remove_team_city"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="game",
            name="games_game_team_id_59a417_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_game_game_da_7a5ecf_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="games_game_created_a2c886_idx",
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[("quick", "Quick Game"), ("team", "Team Game")],
                default="team",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="tracking_mode",
            field=models.CharField(
                choices=[("own_team", "Own Team"), ("both_teams", "Both Teams")],
                default="own_team",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[("quick", "Quick Game"), ("team", "Team Game")],
                default="quick",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="teams.team",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["team", "status", "game_date"],
                name="game_team_status_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["game_type", "status", "game_date"],
                name="game_type_status_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["game_date", "status"],
                name="game_date_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="game_creator_created_idx",
            ),
        ),
    ]
