# Generated by Django 5.2.14 on 2026-05-29 17:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_type_tracking_mode_quick_games'),
        ('teams', '0004_remove_team_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_innings',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('display_name', models.CharField(max_length=150)),
                ('is_tracked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_teams', to='games.game')),
                ('linked_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_team_snapshots', to='teams.team')),
            ],
            options={
                'ordering': ['game_id', 'side', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('batting_order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_team_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_player_snapshots', to='teams.teamplayer')),
                ('game_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gameteam')),
            ],
            options={
                'ordering': ['game_team_id', 'batting_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='gameteam',
            index=models.Index(fields=['game', 'side'], name='games_gamet_game_id_6a9bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='gameteam',
            index=models.Index(fields=['linked_team', 'created_at'], name='games_gamet_linked__39931f_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameteam',
            constraint=models.UniqueConstraint(fields=('game', 'side'), name='unique_game_side'),
        ),
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['game_team', 'is_active', 'batting_order'], name='games_gamep_game_te_107989_idx'),
        ),
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['linked_team_player', 'created_at'], name='games_gamep_linked__197fbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('game_team', 'batting_order'), name='uniq_active_game_order'),
        ),
    ]
