# Generated by Django 5.2.14 on 2026-05-29 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_number_of_innings_gameteam_gameplayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
