# Generated by Django 5.2.14 on 2026-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('quick', 'Quick Game'), ('team', 'Team Game'), ('league', 'League Game')], default='quick', max_length=20),
        ),
    ]
